In [2]:
import numpy as np

A = np.matrix([
    [0, 1, 0, 0],
    [0, 0, 1, 1], 
    [0, 1, 0, 0],
    [1, 0, 1, 0]],
    dtype=float
)

X = np.matrix([
        [i, -i]
        for i in range(A.shape[0])
    ], dtype=float)


In [6]:
A * X

matrix([[ 1., -1.],
        [ 5., -5.],
        [ 1., -1.],
        [ 2., -2.]])

In [7]:
I = np.matrix(np.eye(A.shape[0]))

In [8]:
A_hat = A + I
A_hat * X

matrix([[ 1., -1.],
        [ 6., -6.],
        [ 3., -3.],
        [ 5., -5.]])

In [9]:
D = np.array(np.sum(A, axis=0))[0]
D = np.matrix(np.diag(D))

In [10]:
D**-1 * A

matrix([[0. , 1. , 0. , 0. ],
        [0. , 0. , 0.5, 0.5],
        [0. , 0.5, 0. , 0. ],
        [1. , 0. , 1. , 0. ]])

In [11]:
sample=np.matrix([[1,2],[3,4]])

In [18]:
sample**-2

matrix([[ 5.5 , -2.5 ],
        [-3.75,  1.75]])

In [20]:
from networkx import karate_club_graph, to_numpy_matrix
zkc = karate_club_graph()
order = sorted(list(zkc.nodes()))
A = to_numpy_matrix(zkc, nodelist=order)
I = np.eye(zkc.number_of_nodes())
A_hat = A + I
D_hat = np.array(np.sum(A_hat, axis=0))[0]
D_hat = np.matrix(np.diag(D_hat))

In [21]:
W_1 = np.random.normal(
    loc=0, scale=1, size=(zkc.number_of_nodes(), 4))
W_2 = np.random.normal(
    loc=0, size=(W_1.shape[1], 2))

In [35]:
def relu(x):
    return np.maximum(x, 0)

In [40]:
def gcn_layer(A_hat, D_hat, X, W):
    return relu(D_hat**-1 * A_hat * X * W)
H_1 = gcn_layer(A_hat, D_hat, I, W_1)
H_2 = gcn_layer(A_hat, D_hat, H_1, W_2)
output = H_2

In [41]:
feature_representations = {
    node: np.array(output)[node] 
    for node in zkc.nodes()}

In [42]:
feature_representations

{0: array([0.11385493, 0.66739751]),
 1: array([0.18730671, 0.64200387]),
 2: array([0.42325382, 0.33428477]),
 3: array([0.62392183, 0.54167514]),
 4: array([0.        , 0.52865102]),
 5: array([0.        , 0.45913851]),
 6: array([0.        , 0.55129124]),
 7: array([0.56071992, 0.50673708]),
 8: array([0.04504895, 0.26426801]),
 9: array([0.09232174, 0.13009758]),
 10: array([0.        , 0.58771847]),
 11: array([0.15827874, 1.08049892]),
 12: array([0.84792929, 0.57281318]),
 13: array([0.40681844, 0.32489217]),
 14: array([0.       , 0.7558941]),
 15: array([0.        , 0.49566703]),
 16: array([0.        , 0.49347382]),
 17: array([0.        , 0.78259153]),
 18: array([0.        , 0.70138082]),
 19: array([0.12019304, 0.18625833]),
 20: array([0.        , 0.41864265]),
 21: array([0.        , 0.71356855]),
 22: array([0.       , 0.3671158]),
 23: array([0.0500146 , 0.49763375]),
 24: array([0.18909603, 0.20650772]),
 25: array([0.09128536, 0.2837323 ]),
 26: array([0.03303335, 0.